### ISSUE TITLE
どうやって変えますか？

### ISSUE THREAD

**Issue by monkeycc** [kosuke1701/labelimg-coco-preprocess#1]
dataset/xxx/
├── annotations
│   ├── xxx1.xml
│   ├── xxx2.xml
│   ├── xxx3.xml
│   |   ...
├── images
│   ├── xxx1.jpg
│   ├── xxx2.jpg
│   ├── xxx3.jpg

どうやって変えますか？

**Comment by kosuke1701** [comment]
xmlファイルの中で画像のファイルパスはどのように書かれていますか？
絶対パスになっていれば良いですが、相対パスとなっている場合は基準となっているディレクトリで`convert_to_coco.py`を実行する必要があります。

もしくは、画像ファイルを全て`annotations`ディレクトリに移したうえで

```
python convert_to_coco.py \
    --annotation-fn dataset/annotations/instances_train.json \
    --image-root-dir dataset/train \
    --copy-images --same-dir \
    --annotation-dir dataset/xxx/annotations
```

のようにすると絶対パス、相対パスに関わらず変換ができるはずです。
